/**
 * Mock LLM responses for demo mode
 */
export function generateMockCompletion(
  prompt: string,
  model: string,
  providerId: string
): { completion: string; tokens: number } {
  const lower = prompt.toLowerCase();
  
  // Math responses
  if (lower.includes('calculate') || lower.includes('compute') || lower.includes('what is')) {
    if (lower.includes('2 + 2') || lower.includes('2+2')) {
      return {
        completion: 'The answer is 4.',
        tokens: 15
      };
    }
    if (lower.includes('square root') && lower.includes('144')) {
      return {
        completion: 'The square root of 144 is 12.',
        tokens: 20
      };
    }
    return {
      completion: 'I can help you with that calculation. The result is 42.',
      tokens: 25
    };
  }
  
  // Code responses
  if (lower.includes('function') || lower.includes('code') || lower.includes('implement')) {
    return {
      completion: `Here's a sample implementation:\n\n\`\`\`javascript\nfunction example() {\n  console.log("Hello from ${model}");\n  return true;\n}\n\`\`\``,
      tokens: 80
    };
  }
  
  // Short QA
  if (prompt.includes('?') && prompt.length < 100) {
    return {
      completion: `Based on my understanding, the answer is: This is a response from ${providerId} (${model}). The key point is that it addresses your question directly and concisely.`,
      tokens: 45
    };
  }
  
  // Summarization
  if (lower.includes('summarize') || lower.includes('summary')) {
    return {
      completion: `Summary (generated by ${model}):\n\n- Key Point 1: Main concept identified\n- Key Point 2: Supporting details\n- Key Point 3: Conclusion\n\nThis provides a concise overview of the content.`,
      tokens: 60
    };
  }
  
  // Writing
  if (lower.includes('write') || lower.includes('compose') || lower.includes('draft')) {
    return {
      completion: `Here's a draft response from ${providerId}:\n\nThis is a well-structured piece that addresses your requirements. It includes proper formatting, clear language, and meets the specifications you outlined. The content is original and tailored to your needs.\n\nGenerated by ${model}.`,
      tokens: 95
    };
  }
  
  // Default generic response
  return {
    completion: `Response from ${providerId} (${model}):\n\nI've processed your request: "${prompt.substring(0, 50)}${prompt.length > 50 ? '...' : ''}"\n\nThis is a comprehensive answer that addresses your query with relevant information and context. The response demonstrates understanding of the topic and provides actionable insights.`,
    tokens: 70
  };
}
